### ISSUE TITLE
Socket connection issue on some nodes

### ISSUE THREAD

**Issue by preethamnagesh8** [jhu-ransomware/rSentinel#3]
Socket connection sometimes fails with an error as shown in the screenshot below - 

<img width="672" alt="Screenshot 2023-10-09 at 1 52 31 PM" src="https://github.com/jhu-ransomware/py-distributed-ransomware-defence/assets/20601451/177157cc-76da-4ad1-9a73-97fd7b186971">

**Comment by Crane-Mocker** [comment]
Variable `DEMO_IP` missing in `constants` module. 

`DEMO_IP` is used in `adaptive` modules when calling `communication.send_msg_to_demo_node`, which is after the local file entropy test. Since module `constants` has no attribute `DEMO_IP`, the result is `Socket creation/connection error: timed out`

**Comment by Crane-Mocker** [comment]
All the vars in `constants` are hardcoded, which is a bit problemetic. `constants` should be auto-generated according to the connections configuration.

**Comment by Crane-Mocker** [comment]
Also `send_msg_to_demo_node(constants.DEMO_IP, node_num, diagnosis, constants.NUM_NODES)`. But this function should only take 2 args (`def send_msg_to_demo_node(node_num, arr)`)

**Comment by Crane-Mocker** [comment]
In `def init_demo_socket()`, `sock.connect(('127.0.0.1', constants.DEMO_PORT))`. The socket should connect to another node, instead of localhost.

**Comment by preethamnagesh8** [comment]
Hi Anais, thanks for taking a look at this. For your comment on constants.DEMO_PORT, we might not want to include the DEMO part. This is the UI which was designed for temporary purposes by Nick and Damiano I believe. The remaining comments we can look into.

**Comment by Crane-Mocker** [comment]
> Hi Anais, thanks for taking a look at this. For your comment on constants.DEMO_PORT, we might not want to include the DEMO part. This is the UI which was designed for temporary purposes by Nick and Damiano I believe. The remaining comments we can look into.

Maybe we should just delete this part then. 

I did several tests on my side and I found that when the socket was created, the port on the server side wasn't opened properly.
<img width="706" alt="Screen Shot 2023-10-09 at 7 48 53 PM" src="https://github.com/jhu-ransomware/rSentinel/assets/46662246/e3241868-5da9-4acd-9da5-735064745afe">

You can observe that I modified the code. Here are some modifications I've done on my side:

1. auto generated `constants` module from connections configurations. Since the existence of the `constans.py` and `connections.txt` may leak the IP address in the intranet, we'd better add it to `.gitignore`

2. Converting data type of `test_msg_data`. The status, or the message to send, is a byte-like array with the size of 4 bytes (the size of an integer).

**Comment by preethamnagesh8** [comment]
Resolution - 
1. Multiple socket objects created during testing interval so as to handle the errors
2. Although this is redundant, a workaround would be needed to handle this situation
